###########################################################################################
# Copy and paste this file in your app/config directory and import it in config_dev.yml   #
###########################################################################################

imports:
    - { resource: "UnitTestsConfig.yml" }

logboard:

    All logs:
        enabled: true
        title: All logs
        src: file
        data: %kernel.root_dir%/logs/dev.log
        engine: file_storage
        decompiler: pattern_matcher
        menu:
           date:
               enabled: true
               title: Date
               split:
                   callback: \So\LogboardBundle\Callback\dateFormatter::standardFormat
                   parameter: /^\[([0-9]{4}-[[0-9]{2}-[[0-9]{2}).*/

           priority:
               title: Priority
               split:
                   parameter: /^\[[0-9]{4}-[[0-9]{2}-[[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\]\s[a-z]*\.([a-zA-Z]*).*/

           Events:
               title: Events
               split:
                   parameter: /.*(kernel.[a-zA-Z]*).*/

           Doctrine:
               title: Doctrine
               split:
                   parameter: /.*(Doctrine[^\s\:]*).*/i


#           Events:
#                   split:  /(kernel.[a-zA-Z]*).*(to.*)/
#                   title: Events

#    PHP logs:
#        title: PHP logs
#        src: file
#        data: C:\xampp\php\logs\php_error_log
#        exclude: ~
#        engine: file_storage
#        decompiler: pattern_matcher
#        menu:
#           date:
#                  split: /\[([0-9]{2}-[a-zA-Z]{3}-[0-9]{4})\s[0-9]{2}:[0-9]{2}:[0-9]{2}\s[A-Z]*](.*)/
#                  title: Date
#
#    Apache logs:
#        title: Apache logs
#        src: file
#        data: C:\xampp\apache\logs\error.log
#        exclude: ~
#        engine: file_storage
#        decompiler: pattern_matcher
#        menu:
#           date:
#                  split: /^\[([a-zA-Z0-9\s:.]*)\](.*)/
#                  title: Date
