language: php

php:
  - 5.3

env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: phpunit --coverage-text

