logboard:
    all_logs:
        type: all_logs_priority
        position: 2
        title: all logs
        src: file
        data: %kernel.root_dir%/logs/dev.log
        exclude: ~
        parameters: symfony_file_storage_parameters
        decompiler: pattern_matcher
        split: /^\[[0-9]{4}-[[0-9]{2}-[[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\]\s[a-z]*\.([a-zA-Z]*).\s(.*)$/
